
function maskedRGBImage = createMask(RGB,fruta)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 12-Dec-2024
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

switch fruta
    case 0 %kiwi
        channel1Min = 0.029;
        channel1Max = 0.097;
        channel2Min = 0.231;
        channel2Max = 0.995;
        channel3Min = 0.000;
        channel3Max = 0.720;
        filtrado=0;
    case 1 %pimiento
        channel1Min = 0.146;
        channel1Max = 0.462;
        channel2Min = 0.092;
        channel2Max = 1.000;
        channel3Min = 0.000;
        channel3Max = 1.000;
        filtrado=0;
    case 2 %tomate
       channel1Min = 0.978;
channel1Max = 0.069;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.220;
channel2Max = 0.969;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.696;
channel3Max = 1.000;
        filtrado=1;

    case 3 % berenjena
        channel1Min = 0.034;
        channel1Max = 0.031;
        channel2Min = 0.000;
        channel2Max = 0.727;
        channel3Min = 0.000;
        channel3Max = 0.327;
        filtrado=1;

    case 4 %limon
        channel1Min = 0.072;
channel1Max = 0.201;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.449;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.646;
channel3Max = 1.000;

        filtrado=0;

    case 5 %mandarina
        channel1Min = 0.034;
        channel1Max = 0.119;
        channel2Min = 0.164;
        channel2Max = 1.000;
        channel3Min = 0.796;
        channel3Max = 1.000;
        filtrado=0;

    case 6 %zanahoria
        channel1Min = 0.044;
        channel1Max = 0.080;
        channel2Min = 0.308;
        channel2Max = 1.000;
        channel3Min = 0.670;
        channel3Max = 1.000;

        filtrado=0;

end

switch filtrado
    case 0
        sliderBW = ( (I(:,:,1) >= channel1Min) & (I(:,:,1) <= channel1Max) ) & ...
            (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
            (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
    case 1
        sliderBW = ( (I(:,:,1) >= channel1Min) | (I(:,:,1) <= channel1Max) ) & ...
            (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
            (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
end
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end